### ISSUE TITLE
Missing Binaries and/or Incompatibility Issue with Unreal Engine 4.18.3

### ISSUE THREAD

**Issue by berkayalpcakal** [robcog-iai/URoboSim-depr#16]
Hello,

First of all, thank you for publishing such an amazing work. As Siemens, we would like the evaluate this plugin and compare it with the [plugin](https://github.com/siemens/ros-sharp) we have for importing .urdf models into Unity3D. 

Which version of Unreal Engine is it that you tested URoboSim plugin?
We have been trying it with the version 4.18.3, but getting an error like this;

> Missing Plugin
> Binaries for the 'URoboSim' plugin are missing or incompatible with the current engine version.

Passionately looking forward to get an answer from you!

Kind Regards
Berkay Alp Cakal.

**Comment by andreihaidu** [comment]
Hi Berkay,

the plugin should be compatible with 4.18. Try removing the Binaries and Intermediate folders and recompile.

The robot sim might not be very useful though, since it was more a proof of concept, and it has very hacky code inside. It will need major refactoring in the future. However you could easily cherrypick various code for your need at this point.

Cheers,
Andrei
